# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

# Docker services
services:
  - docker:dind

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

# Always build a dev image. This container will be used in follow up jobs.
build:
  stage: build
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10-alpine yarn install
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10-alpine yarn build
    - docker build . -t pollex/portal:dev
    - docker save pollex/portal:dev | gzip > portal_image.tar.gz
  artifacts:
    paths:
      - dist/
      - portal_image.tar.gz

# Use the dev image with the repo mounted to perform tests.
test:
  stage: test
  dependencies:
    - build
  before_script:
    - docker load --input portal_image.tar.gz
    - docker run --rm -w /srv/app -v $(pwd):/srv/app pollex/portal:dev yarn install
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app pollex/portal:dev yarn test
  artifacts:
    paths:
      - coverage/

# When this is a build on the master branch, tag the image with :latest
# and push it to the image repository.
deploy:master:
  stage: deploy
  dependencies:
    - build
  before_script:
    - docker load --input portal_image.tar.gz
    - mkdir -p ~/.docker
    - echo $DOCKER_ACCESS_CONFIG > ~/.docker/config.json
  script:
    - docker tag pollex/portal:dev pollex/portal:latest
    - docker push pollex/portal:latest
  only:
    - master


# When this is a build on the dev branch, tag the image with :edge
# and push it to the image repository.
deploy:edge:
  stage: deploy
  dependencies:
    - build
  before_script:
    - docker load --input portal_image.tar.gz
    - mkdir -p ~/.docker
    - echo $DOCKER_ACCESS_CONFIG > ~/.docker/config.json
  script:
    - docker tag pollex/portal:dev pollex/portal:edge
    - docker push pollex/portal:edge
  only:
    - dev