# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

# Docker services
services:
  - docker:dind

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

# Build the project source and container
build:container:
  stage: build
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10-alpine yarn install
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10-alpine yarn build
    - docker build . -t pollex/portal
    - docker save pollex/portal | gzip > portal_image.tar.gz
  artifacts:
    paths:
      - dist/
      - portal_image.tar.gz

# Test through the built container
test:
  stage: test
  dependencies:
    - build:container
  before_script:
    - docker load --input portal_image.tar.gz
    - docker run --rm -w /srv/app -v $(pwd):/srv/app pollex/portal yarn install
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app pollex/portal yarn test
  artifacts:
    paths:
      - coverage/

# Deploy the previously built container to the Docker registery
deploy:container:
  stage: deploy
  dependencies:
    - build:container
  before_script:
    - docker load --input portal_image.tar.gz
    - mkdir -p ~/.docker
    - echo $DOCKER_ACCESS_CONFIG > ~/.docker/config.json
  script:
    - docker push pollex/portal
  # only:
  #   - master