# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using the Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how the Kubernetes executor connects services
  # to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  # For non-Kubernetes executors, we use tcp://docker:2375
  DOCKER_HOST: tcp://docker:2375
  #
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

# Docker services
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

# Build the project source and container
build:container:
  stage: build
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10 yarn install
    - docker run --rm -w /srv/app -v $(pwd):/srv/app node:10 yarn build
    - docker build . -t portal
  artifacts:
    paths:
      - dist/

# Test through the built container
test:
  stage: test
  script:
    - docker run --rm -w /srv/app -v $(pwd):/srv/app portal yarn test
  artifacts:
    paths:
      - coverage/

# Deploy the previously built container to the Docker registery
deploy:container:
  stage: deploy
  script:
    - echo $DOCKER_ACCESS_TOKEN | docker login --username timvosch --password-stdin
    - docker push pollex/portal:latest
  # only:
  #   - master