# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Docker services
# services:
#   - mongo:latest

stages:
  - test
  - package
  - deploy

test:
  stage: test
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn test
  artifacts:
    paths:
      - coverage/

package_production:
  stage: package
  script:
    - yarn compile
  artifacts:
    name: "package-$CI_COMMIT_SHA"
    paths:
      - dist/
  # when:
  #   - tag

deploy_production:
  stage: deploy
  script:
    - echo $PRODUCTION_URL
  environment:
    name: production
  # only:
  #   - master
  