---
- hosts: servers
  remote_user: "{{ deploy_user }}"
  tasks:
    - name: Checkout repository
      git:
        repo: "{{ source_repository }}"
        dest: "{{ deploy_path }}"
        version: "{{ source_version }}"
        force: yes
    
    - name: Install dependencies
      shell: cd {{ deploy_path }} && yarn --production
    
    - name: Copy transpiled code
      copy:
        src: ../dist
        dest: "{{ deploy_path }}/"
        owner: "{{ deploy_user }}"
    
    - name: Start updated servers
      shell: cd {{ deploy_path }} && yarn run start:prod
    
    - name: Save ecosystem to startup
      command: pm2 save