# This playbook ensures that the user portal exists
# and has proper permissions.
#
# You should have super user rights on the target
# servers. (Also see -K parameter)

---
- hosts: servers
  become: true
  roles:
    - nodejs
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    
    - name: Ensure user {{ deploy_user }} exists
      user:
        name: "{{ deploy_user }}"
        state: present
        group: wheel
        append: yes
        home: "/home/{{ deploy_user }}"
    
    - name: Authorize SSH
      authorized_key:
        user: portal
        state: present
        key: "{{ lookup('file', './keypairs/deploy_key.pub') }}"
    
    - name: Ensure deploy location exists
      file:
        owner: "{{ deploy_user }}"
        path: "{{ deploy_path }}"
        state: directory
      
    - name: Install yarn (package manager)
      npm:
        name: yarn
        global: yes
      
    - name: Install PM2 (process manager)
      npm:
        name: pm2
        global: yes

    - name: Setup PM2 for start up
      become: no
      remote_user: "{{ deploy_user }}"
      shell: "pm2 startup | sed -n '/the following command/{n;p;}' | bash"